services:
  app-server:
    container_name: vehicle-app
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: unless-stopped