services:
  app-server:
    build: .
    container_name: vehicle-app
    restart: unless-stopped
    ports:
      - '${PORT:-4000}:4000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"